create:
  is_secure: true
  credentials: [ "Create Season" ]
edit:
  is_secure: true
  credentials: [ "Edit Season" ]
delete:
  is_secure: true
  credentials: [ "Delete Season" ]
index:
  is_secure: true
  credentials: [ "View Season" ]