create:
  is_secure: true
  credentials: [ "User Management" ]
edit:
  is_secure: true
  credentials: [ "User Management" ]
delete:
  is_secure: true
  credentials: [ "User Management" ]
index:
  is_secure: true
  credentials: [ "User Management" ]