Matchs:
  actAs:
    Timestampable: ~
  columns:
    id: { primary: true, type: integer(20), autoincrement: true }
    ip: { type: varchar(50) }
    server_id: { type: integer(20) }
    team_a: { type: varchar(255) }
    team_b: { type: varchar(255) }
    status: { type: integer(2) }
    score_a: { type: integer(5) }
    score_b: { type: integer(5) }
    max_round: { type: integer(3) }
    rules: { type: varchar(200) }
    config_full_score: { type: boolean }
    config_ot: { type: boolean }
    config_knife_round: { type: boolean }
    config_switch_auto: { type: boolean }
    config_auto_change_password: { type: boolean }
    config_password: { type: varchar(50) }
    config_heatmap: { type: boolean }
    enable: { type: boolean }
    current_map: { type: integer(20) }
    force_zoom_match: { type: boolean }
  relations:
    Server: { class: Servers, onDelete: CASCADE, local: server_id, foreign: id }
    Map: { class: Maps, onDelete: CASCADE, local: current_map, foreign: id }

Maps:
  actAs:
    Timestampable: ~
  columns:
    id: { primary: true, type: integer(20), autoincrement: true }
    match_id: { type: integer(20), notnull: true }
    map_name: { type: varchar(50) }
    score_1: { type: integer(5) }
    score_2: { type: integer(5) }
    current_side: { type: enum, values: [ ct, t ] }
    status: { type: integer(3) }
    maps_for: { type: enum, values: [ default, team1, team2 ]}
    nb_ot: { type: integer(20) }
  relations:
    Match: { class: Matchs, onDelete: CASCADE, local: match_id, foreign: id }
    
MapsScore:
  actAs:
    Timestampable: ~
  columns:
    id: { primary: true, type: integer(20), autoincrement: true }
    map_id: { type: integer(20), notnull: true }
    type_score: { type: enum, values: [ normal, ot ] }
    score1_side1: { type: integer(5) }
    score1_side2: { type: integer(5) }
    score2_side1: { type: integer(5) }
    score2_side2: { type: integer(5) }
  relations:
    Map: { class: Maps, onDelete: CASCADE, local: map_id, foreign: id }
    
Players:
  actAs:
    Timestampable: ~
  columns:
    id: { primary: true, type: integer(20), autoincrement: true }
    match_id: { type: integer(20), notnull: true }
    map_id: { type: integer(20), notnull: true }
    player_key: { type: varchar(255) }
    team: { type: enum, values: [ a,b,other], default: other}
    ip: { type: varchar(255) }
    steamid: { type: varchar(255) }
    first_side: { type: enum, values: [ ct, t, other ] }
    current_side: { type: enum, values: [ ct, t, other ] }
    pseudo: { type: varchar(255) }
    nb_kill: { type: integer(5), default: 0 }
    assist: { type: integer(5), default: 0 }
    death: { type: integer(5), default: 0 }
    point: { type: integer(5), default: 0 }
    hs: { type: integer(5), default: 0 }
    defuse: { type: integer(5), default: 0 }
    bombe: { type: integer(5), default: 0 }
    tk: { type: integer(5), default: 0 }
    nb1: { type: integer(5), default: 0 }
    nb2: { type: integer(5), default: 0 }
    nb3: { type: integer(5), default: 0 }
    nb4: { type: integer(5), default: 0 }
    nb5: { type: integer(5), default: 0 }
    nb1kill: { type: integer(5), default: 0 }
    nb2kill: { type: integer(5), default: 0 }
    nb3kill: { type: integer(5), default: 0 }
    nb4kill: { type: integer(5), default: 0 }
    nb5kill: { type: integer(5), default: 0 }
    pluskill: { type: integer(5), default: 0 }
    firstkill: { type: integer(5), default: 0 }
  relations:
    Match: { class: Matchs, onDelete: CASCADE, local: match_id, foreign: id }
    Map: { class: Maps, onDelete: CASCADE, local: map_id, foreign: id }

Round:
  actAs:
    Timestampable: ~
  columns:
    id: { primary: true, type: integer(20), autoincrement: true }
    match_id: { type: integer(20), notnull: true }
    map_id: { type: integer(20), notnull: true }
    event_name: { type: varchar(255) }
    event_time: { type: integer(5) }
    killer_id: { type: integer(20) }
    killed_id: { type: integer(20) }
    round_id: { type: integer(20) }
  relations:
    Match: { class: Matchs, onDelete: CASCADE, local: match_id, foreign: id }
    Map: { class: Maps, onDelete: CASCADE, local: map_id, foreign: id }
    Killer: { class: Players, onDelete: SET NULL, local: killer_id, foreign: id }
    Killed: { class: Players, onDelete: SET NULL, local: killed_id, foreign: id }

RoundSummary:
  actAs:
    Timestampable: ~
  columns:
    id: { primary: true, type: integer(20), autoincrement: true }
    match_id: { type: integer(20), notnull: true }
    map_id: { type: integer(20), notnull: true }
    bomb_planted: { type: boolean }
    bomb_defused: { type: boolean }
    bomb_exploded: { type: boolean }
    win_type: { type: enum, values: [ bombdefused, bombeexploded, normal, saved], default: normal }
    team_win: { type: enum, values: [ a, b ]}
    ct_win: { type: boolean }
    t_win: { type: boolean }
    best_killer: { type: integer(5) }
    best_killer_fk: { type: boolean }
    best_action_type: { type: text }
    best_action_param: { type: text }
    round_id: { type: integer(5) }
  relations:
    Match: { class: Matchs, onDelete: CASCADE, local: match_id, foreign: id }
    Map: { class: Maps, onDelete: CASCADE, local: map_id, foreign: id }

PlayerKill:
  actAs:
    Timestampable: ~
  columns:
    id: { primary: true, type: integer(20), autoincrement: true }
    match_id: { type: integer(20), notnull: true }
    map_id: { type: integer(20), notnull: true }
    killer_name: { type: varchar(100) }
    killer_id: { type: integer(20) }
    killed_name: { type: varchar(100) }
    killed_id: { type: integer(20) }
    weapon: { type: varchar(100) }
    headshot: { type: boolean }
    round_id: { type: integer(5) } 
  relations:
    Match: { class: Matchs, onDelete: CASCADE, local: match_id, foreign: id }
    Map: { class: Maps, onDelete: CASCADE, local: map_id, foreign: id }
    Killer: { class: Players, onDelete: CASCADE, local: killer_id, foreign: id }
    Killed: { class: Players, onDelete: CASCADE, local: killed_id, foreign: id }
    
PlayersHeatmap:
  actAs:
    Timestampable: ~
  columns:
    id: { primary: true, type: integer(20), autoincrement: true }
    match_id: { type: integer(20), notnull: true }
    map_id: { type: integer(20), notnull: true }
    event_name: { type: varchar(50) }
    event_x: { type: integer(5) }
    event_y: { type: integer(5) }
    event_z: { type: integer(5) }
    player_id: { type: integer(20) }
    player_team: { type: varchar(20) }
    attacker_x: { type: integer(5) }
    attacker_y: { type: integer(5) }
    attacker_z: { type: integer(5) }
    attacker_team: { type: varchar(20) }
    round_id: { type: integer(5) }
    round_time: { type: integer(20) }
  relations:
    Match: { class: Matchs, onDelete: CASCADE, local: match_id, foreign: id }
    Map: { class: Maps, onDelete: CASCADE, local: map_id, foreign: id }
    Player: { class: Players, onDelete: CASCADE, local: player_id, foreign: id }
    
Servers:
  actAs:
    Timestampable: ~
  columns:
    id: { primary: true, type: integer(20), autoincrement: true }
    ip: { type: varchar(50), notnull: true }
    rcon: { type: varchar(50), notnull: true }
    hostname: { type: varchar(100), notnull: true }
    tv_ip: { type: varchar(100) }    